# Generated by Django 5.1.7 on 2025-03-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_created_at_alter_blog_updated_at_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
