# Generated by Django 5.1.7 on 2025-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_blog_comment_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
