# Generated by Django 5.1.7 on 2025-03-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
    ]
