# Generated by Django 5.1.7 on 2025-03-24 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
