# Generated by Django 5.1.7 on 2025-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_comment_uid_comment_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='coment_id',
        ),
    ]
