# Generated by Django 5.1.7 on 2025-03-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_comment_id_comment_coment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
