# Generated by Django 5.1.7 on 2025-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_bloglike_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='like_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='like_status',
            field=models.BooleanField(default=True),
        ),
    ]
